location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    ingress:
      external: true
      targetPort: {{ targetPortOrDefault 8080 }}
      transport: http
      allowInsecure: true
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: connectionstrings--assistant-db
        value: Host=postgres;Port=5432;Username=postgres;Password={{ securedParameter "PostgresDatabasePassword" }};Database=assistant-db
      - name: connectionstrings--language-model
        value: '{{ .Env.LANGUAGE_MODEL_CONNECTIONSTRING }}'
      - name: connectionstrings--vector-db
        value: Endpoint=http://vector-db.internal.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }};Key={{ securedParameter "VectorDatabaseApiKey" }}
      - name: connectionstrings--vector-db-http
        value: Endpoint=http://vector-db:6333;Key={{ securedParameter "VectorDatabaseApiKey" }}
      - name: connectionstrings--app-insights
        value: InstrumentationKey={{ .Env.APP_INSIGHTS_APPINSIGHTSCONNECTIONSTRING }}
  template:
    containers:
      - image: {{ .Image }}
        name: assistant
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
            value: in_memory
          - name: ConnectionStrings__assistant-db
            secretRef: connectionstrings--assistant-db
          - name: ConnectionStrings__language-model
            secretRef: connectionstrings--language-model
          - name: ConnectionStrings__vector-db
            secretRef: connectionstrings--vector-db
          - name: ConnectionStrings__vector-db_http
            secretRef: connectionstrings--vector-db-http
    scale:
      minReplicas: 1
tags:
  azd-service-name: assistant
  aspire-resource-name: assistant
